spring:
  application:
    name: Journal-Management-Application

server:
  port: 9090

# Default profile (local)
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/journal-management?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: user123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql-db:3306/journal-management?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: user123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
